// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart'; 
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1xChkYosDcpzIlZpufoVMrYL0E8yYr1Y',
    appId: '1:713651641836:web:4b25249cfe788fe670b4c9',
    messagingSenderId: '713651641836',
    projectId: 'fir-main-f6d0e',
    authDomain: 'fir-main-f6d0e.firebaseapp.com',
    storageBucket: 'fir-main-f6d0e.firebasestorage.app',
    measurementId: 'G-DS5MCCHQTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-po1JRN0PeC9CkgN-fZiZCTBixL1XCK4',
    appId: '1:713651641836:android:7514a03557c35bdc70b4c9',
    messagingSenderId: '713651641836',
    projectId: 'fir-main-f6d0e',
    storageBucket: 'fir-main-f6d0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1hsWMM8dN0rvLkuDq29wIF_SNZm4sI2A',
    appId: '1:713651641836:ios:c2da95699c118f7270b4c9',
    messagingSenderId: '713651641836',
    projectId: 'fir-main-f6d0e',
    storageBucket: 'fir-main-f6d0e.firebasestorage.app',
    iosBundleId: 'com.example.firebasemain1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1hsWMM8dN0rvLkuDq29wIF_SNZm4sI2A',
    appId: '1:713651641836:ios:c2da95699c118f7270b4c9',
    messagingSenderId: '713651641836',
    projectId: 'fir-main-f6d0e',
    storageBucket: 'fir-main-f6d0e.firebasestorage.app',
    iosBundleId: 'com.example.firebasemain1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1xChkYosDcpzIlZpufoVMrYL0E8yYr1Y',
    appId: '1:713651641836:web:a6cbe0808283ee1e70b4c9',
    messagingSenderId: '713651641836',
    projectId: 'fir-main-f6d0e',
    authDomain: 'fir-main-f6d0e.firebaseapp.com',
    storageBucket: 'fir-main-f6d0e.firebasestorage.app',
    measurementId: 'G-9ZXZYCT2VT',
  );

}